@startuml Colaboracion_Login
title Diagrama de Colaboración - Iniciar Sesión
skinparam Style strictuml

object "Usuario : Actor" as Usuario
object "vista : InterfazLogin" as Vista
object "ctrl : ControlAutenticacion" as Ctrl
object "usuarioDao : UsuarioDAO" as DAO
object "bd : ConexionBD" as BD

Usuario --> Vista : 1: iniciarSesion()
Vista --> Ctrl : 1.2: iniciar_sesion(correo, contrasenia)
Ctrl --> DAO : 1.2.1: iniciar_sesion(correo, contrasenia)
DAO --> BD : 1.2.1.1: ejecutar_consulta()
BD --> DAO : 1.2.1.2: fila_usuario
DAO --> Ctrl : 1.2.2: usuario o None
Ctrl --> Vista : 1.3: resultado
Vista --> Usuario : 1.4: abrir_panel o mostrar_error

@enduml