@startuml Colaboracion_Asignar_Rutina
title Diagrama de Colaboración - Asignar Rutina a Cliente
skinparam Style strictuml

object "Admin : Actor" as Admin
object "vista : InterfazGestionRutinas" as Vista
object "ctrl : ControlRutinas" as Ctrl
object "asigDao : AsignacionRutinaDAO" as AsigDAO
object "bd : ConexionBD" as BD

Admin --> Vista : 1: asignarRutina()
Vista --> Ctrl : 1.1: asignar_rutina(idCliente, idRutina)
Ctrl --> AsigDAO : 1.1.1: buscar_activa(idCliente)
AsigDAO --> BD : 1.1.1.1: ejecutar_consulta()
BD --> AsigDAO : 1.1.1.2: asignacion_activa o None
AsigDAO --> Ctrl : 1.1.2: asignacion_activa
Ctrl --> AsigDAO : 1.1.3: actualizar(estado=FINALIZADA)
AsigDAO --> BD : 1.1.3.1: ejecutar_actualizacion()
BD --> AsigDAO : 1.1.3.2: True
AsigDAO --> Ctrl : 1.1.3.3: asignacion_finalizada
Ctrl --> AsigDAO : 1.1.4: guardar(nueva_asignacion)
AsigDAO --> BD : 1.1.4.1: ejecutar_actualizacion()
BD --> AsigDAO : 1.1.4.2: id_asignacion
AsigDAO --> Ctrl : 1.1.5: True
Ctrl --> Vista : 1.2: True
Vista --> Admin : 1.3: mostrar_mensaje()

@enduml